export const COACHES = [
  {
    id: 1,
    slug: "carlos-silva",
    name: "Carlos Silva",
    description: "Com mais de 12 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Técnico Principal",
    location: "São Paulo, SP",
    rating: 4.9,
    experience: "15 anos",
    achievements: "3 Títulos Estaduais",
    players: 45,
    price: "R$ 200/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 2,
    slug: "ana-santos",
    name: "Ana Santos",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Preparadora Física",
    location: "Rio de Janeiro, RJ",
    rating: 4.8,
    experience: "12 anos",
    achievements: "Especialista FIFA",
    players: 32,
    price: "R$ 150/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 3,
    slug: "roberto-lima",
    name: "Roberto Lima",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Treinador de Goleiros",
    location: "Belo Horizonte, MG",
    rating: 5.0,
    experience: "20 anos",
    achievements: "Ex-Goleiro Profissional",
    players: 28,
    price: "R$ 180/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 4,
    slug: "fernanda-costa",
    name: "Fernanda Costa",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Analista Tática",
    location: "Porto Alegre, RS",
    rating: 4.7,
    experience: "8 anos",
    achievements: "Mestrado em Ciências do Esporte",
    players: 38,
    price: "R$ 120/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 5,
    slug: "miguel-rodriguez",
    name: "Miguel Rodriguez",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Técnico Juvenil",
    location: "Curitiba, PR",
    rating: 4.9,
    experience: "18 anos",
    achievements: "Campeão Brasileiro Sub-20",
    players: 52,
    price: "R$ 160/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 6,
    slug: "juliana-mendes",
    name: "Juliana Mendes",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Psicóloga Esportiva",
    location: "Salvador, BA",
    rating: 4.8,
    experience: "10 anos",
    achievements: "Especialista em Performance Mental",
    players: 41,
    price: "R$ 140/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 7,
    slug: "andre-souza",
    name: "André Souza",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Treinador de Futebol",
    location: "Fortaleza, CE",
    rating: 4.6,
    experience: "9 anos",
    achievements: "Campeão Cearense",
    players: 30,
    price: "R$ 130/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 8,
    slug: "patricia-almeida",
    name: "Patrícia Almeida",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Treinadora de Futebol Feminino",
    location: "Belo Horizonte, MG",
    rating: 4.9,
    experience: "11 anos",
    achievements: "Campeã Mineira Feminina",
    players: 25,
    price: "R$ 150/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 9,
    slug: "lucas-oliveira",
    name: "Lucas Oliveira",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeão. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Treinador de Futebol",
    location: "São Paulo, SP",
    rating: 4.8,
    experience: "10 anos",
    achievements: "Campeão Paulista",
    players: 35,
    price: "R$ 140/hora",
    image: "/shadcn.jpg",
  },
  {
    id: 10,
    slug: "maria-silva",
    name: "Maria Silva",
    description: "Com mais de 15 anos, minha paixão é transformar potencial em excelência. Minha metodologia é focada em desenvolver não apenas as habilidades técnicas e táticas, mas também a mentalidade de campeã. Já treinei 32 atletas, ajudando-os a alcançar marcos importantes em suas carreiras.",
    specialty: "Treinadora de Futebol Feminino",
    location: "Rio de Janeiro, RJ",
    rating: 4.9,
    experience: "11 anos",
    achievements: "Campeã Carioca Feminina",
    players: 27,
    price: "R$ 150/hora",
    image: "/shadcn.jpg",
  }
];
