export const PLAYERS = [
  {
    id: 1,
    slug: "joao-pedro",
    name: "João Pedro",
    description: "Atleta dedicado e focado em constante evolução, buscando uma oportunidade para demonstrar meu talento e contribuir para o sucesso de uma equipe. Tenho grande capacidade de adaptação tática e um forte comprometimento com os objetivos do time.",
    position: "Atacante",
    age: 19,
    location: "São Paulo, SP",
    goals: 24,
    matches: 30,
    level: "Semi-Profissional",
    height: "1.78m",
    weight: "72kg",
    image: "/shadcn.jpg",
  },
  {
    id: 2,
    slug: "maria-oliveira",
    name: "Maria Oliveira",
    description: "Atleta versátil e criativa, sempre em busca de novas estratégias para superar desafios. Estou pronta para contribuir com minha visão de jogo e habilidades técnicas.",
    position: "Meio-Campo",
    age: 22,
    location: "Rio de Janeiro, RJ",
    goals: 8,
    matches: 28,
    level: "Profissional",
    height: "1.65m",
    weight: "58kg",
    image: "/shadcn.jpg",
  },
  {
    id: 3,
    slug: "lucas-santos",
    name: "Lucas Santos",
    description: "Zagueiro sólido e confiável, sempre pronto para proteger a defesa e contribuir para o jogo coletivo. Minha leitura de jogo e posicionamento são minhas maiores forças.",
    position: "Zagueiro",
    age: 20,
    location: "Belo Horizonte, MG",
    goals: 3,
    matches: 32,
    level: "Semi-Profissional",
    height: "1.85m",
    weight: "78kg",
    image: "/shadcn.jpg",
  },
  {
    id: 4,
    slug: "gabriel-costa",
    name: "Gabriel Costa",
    description: "Goleiro ágil e atento, sempre pronto para defender a meta e organizar a defesa. Minha comunicação e posicionamento são fundamentais para o sucesso do time.",
    position: "Goleiro",
    age: 18,
    location: "Porto Alegre, RS",
    goals: 0,
    matches: 25,
    level: "Juvenil",
    height: "1.88m",
    weight: "82kg",
    image: "/shadcn.jpg",
  },
  {
    id: 5,
    slug: "amanda-silva",
    name: "Amanda Silva",
    position: "Lateral",
    age: 21,
    location: "Brasília, DF",
    goals: 5,
    matches: 29,
    level: "Semi-Profissional",
    description: "Jogadora ágil e defensiva, sempre pronta para apoiar o ataque e proteger a defesa. Minha versatilidade me permite atuar em várias posições.",
    height: "1.68m",
    weight: "60kg",
    image: "/shadcn.jpg",
  },
  {
    id: 6,
    slug: "rafael-mendes",
    name: "Rafael Mendes",
    description: "Volante experiente e estratégico, sempre buscando interceptar jogadas e iniciar contra-ataques. Minha visão de jogo e passes precisos são minhas principais características.",
    position: "Volante",
    age: 23,
    location: "Salvador, BA",
    goals: 6,
    matches: 31,
    level: "Profissional",
    height: "1.75m",
    weight: "70kg",
    image: "/shadcn.jpg",
  },
  {
    id: 7,
    slug: "carla-rodrigues",
    name: "Carla Rodrigues",
    description: "Atleta versátil e criativa, sempre em busca de novas estratégias para superar desafios. Estou pronta para contribuir com minha visão de jogo e habilidades técnicas.",
    position: "Atacante",
    age: 20,
    location: "Curitiba, PR",
    goals: 15,
    matches: 27,
    level: "Profissional",
    height: "1.70m",
    weight: "65kg",
    image: "/shadcn.jpg",
  },
  {
    id: 8,
    slug: "pedro-almeida",
    name: "Pedro Almeida",
    description: "Meio-campista criativo e dinâmico, sempre em busca de espaços para criar jogadas. Minha visão de jogo e passes precisos são minhas principais características.",
    position: "Meio-Campo",
    age: 24,
    location: "Fortaleza, CE",
    goals: 10,
    matches: 30,
    level: "Semi-Profissional",
    height: "1.80m",
    weight: "75kg",
    image: "/shadcn.jpg",
  },
  {
    id: 9,
    slug: "luan-souza",
    name: "Luan Souza",
    description: "Zagueiro sólido e confiável, sempre pronto para proteger a defesa e contribuir para o jogo coletivo. Minha leitura de jogo e posicionamento são minhas maiores forças.",
    position: "Zagueiro",
    age: 21,
    location: "Recife, PE",
    goals: 2,
    matches: 28,
    level: "Profissional",
    height: "1.82m",
    weight: "80kg",
    image: "/shadcn.jpg",
  },
  {
    id: 10,
    slug: "bianca-souza",
    name: "Bianca Souza",
    description: "Atleta dedicada e focada em constante evolução, buscando uma oportunidade para demonstrar meu talento e contribuir para o sucesso de uma equipe. Tenho grande capacidade de adaptação tática e um forte comprometimento com os objetivos do time.",
    position: "Atacante",
    age: 22,
    location: "São Paulo, SP",
    goals: 12,
    matches: 30,
    level: "Profissional",
    height: "1.75m",
    weight: "68kg",
    image: "/shadcn.jpg",
  },
];
